### PR TITLE
disable systemd-nspawn in mock. Fixes #74

### LINKED ISSUE #74: mock and systemd nspawn
note to self:
config_opts['use_nspawn'] = False
to
- docs
- example config el7
- example config el6
if in testing I continue having issues with mock builds with the latest mock

### PR DESCRIPTION
**Pull request by pcfe**

### CODE REVIEW

**Comment by pcfe** [comment]
tested at home and at $current_customer.

Still unsure why I get the failure on a RHEL7 machine building RHEL7 packages, but disabling the new nspawn functionality in mock makes the builds work as they were working previously.

**Comment by evgeni** [comment]
IMHO ok.
I wonder if the EL6 change is needed, as that does not even have systemd.

**Comment by pcfe** [comment]
I put it in the el6 mock config as mock runs on el7 here for both my el6 and el7 builds.
Want me to test an el6 mock config without the line on my build host?

**Comment by evgeni** [comment]
Nah. I'm good.

**Pull request merged**
