### PR TITLE
Introduce pipeline as code

### PR DESCRIPTION
**Pull request by jeichler**
@ericzolf pcfe thought you might want to have a look and play around.
basically this PR introduces the pipeline as code (aka Jenkinsfile). furthermore it combines the puppet-only feature with the rpm builds in one build job.
the beauty of it, is of course, that it's easy and maintained in the SCM (right now just git - other SCMs are on my feature list). so changes in your pipeline are treated as code changes. 
PR #71 should be merged before testing this, according to @pcfe

### CODE REVIEW

**Comment by evgeni** [comment]
not strictly related to this PR, but can't we use jenkins-job-builder instead of dumping XML? it's so hard to read :(

**Comment by jeichler** [comment]
@evgeni i'm not a fan of xml either - i see what i can do. but not in this PR.

**Comment by jeichler** [comment]
might be a good idea to show how it looks like.
pipeline

**Comment by nstrug** [comment]
Hi Janine - thanks for the PR. We are going to pull this into a branch for the time being - it's definitely something we want to be doing.

**Pull request closed without merging**
